### ISSUE TITLE
springdoc-openapi-ui: overwrite dummy data to info section(title, description) of openapi spec document.

### ISSUE THREAD

**Issue by traeper** [springdoc/springdoc-openapi#1042]
I am using springdoc-openapi library gratefully. I may have made a mistake, but I do not understand the phenomenon, so I report the issue. 🙏 

**Describe the bug**
- I generated openapi3 spec file 'myApiSpec.yml' and integrated with springdoc-openapi-ui. But myApiSpec title, version, description is disappeared and Dummy data **(title : 'OpenAPI definition', version : 'v0')** is inserted. There is no ploblem in another API spec data. 
- Contents of myApiSpec.yml file is not changed. This problem is appeared after boot application started and I connect custom springdoc.api-docs.path (/static/myApiSpec.yml)

**To Reproduce**
- What version of spring-boot you are using? **2.3.4.RELEASE**
- What modules and versions of springdoc-openapi are you using? **1.5.2**
- Provide with a sample code (HelloController) or Test that reproduces the problem

- myApiSpec.yml
```yml
openapi: 3.0.1
info:
  title: my api
  description : my description
  version: 0.0.1
servers:
- url: http://localhost:8080
tags: []
paths:
.... omit api spec part ....
```

  - application.yml
```yml
springdoc:
  api-docs:
    path: /static/myApiSpec.yml # json extension has same problem.
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /**
```

- Actually I got /static/myApiSpec.yml after boot application started. title, version is changed to dummy data. But another API spec data is not changed.
```json 
{"openapi":"3.0.1","info":{"title":"OpenAPI definition","version":"v0", .... }}}
```

**Expected behavior**
- A clear and concise description of what you expected to happen. : I hope that myApiSpec.yml data is not overwritten. Expected data is **title : "my api", version: "0.0.1", description: "my description"**
