### ISSUE TITLE
Spring Data Rest: Allow to override required attribute when @NotNull is set

### ISSUE THREAD

**Issue by mathias-ewald** [springdoc/springdoc-openapi#1094]
**Describe the bug**
When I annotate an entity property with `@NotNull`, I required this property to be set on the persistence layer. For most situations, it makes sense to assume it is required on the REST layer, too. In my scenario, I have such a property that is not required on the REST layer but will be filled in by application logic if not set. 

**To Reproduce**
Springboot: 2.4.3
Springdoc: 1.5.5

Any entity with a `@NotNull` property will do to reproduce:

```
public class Pet {
	@NotNull
	private String name;
}
```
```
    Pet:
      required:
      - name
      type: object
      properties:
        name:
          type: string
```

**Expected behavior**
I would expect an annotation like `@Schema(required = false)` on the `name` property to override the the `@NotNull` in the context of the api doc.
