### ISSUE TITLE
Collection methods are added to the supported entity methods

### ISSUE THREAD

**Issue by bschoenmaeckers** [springdoc/springdoc-openapi#1105]
**Describe the bug**
When disabling all single entity access methods and only allowing whole collection endpoints like in the repository bellow. Spring doc will still show a GET method endpoint for a single entity via an ID. The corresponding endpoint will return 405 (Method not allowed) because it is disabled.

generated yaml:

```yaml
  /notifications:
    get:
      description: get-notification
    ......
  /notifications/{id}:
    get:
      description: get-notification
    ......
```

**To Reproduce**
Using springdoc 1.5.4

```java
@RepositoryRestResource
public interface NotificationRepository extends PagingAndSortingRepository<Notification, Long> {

    //This should be the only available endpoint
    @Override
    @RestResource
    List<Notification> findAll();

    @Override
    @RestResource(exported = false)
    Optional<Notification> findById(Long aLong);

    @Override
    @RestResource(exported = false)
    <S extends Notification> S save(S entity);

    @Override
    @RestResource(exported = false)
    void deleteById(Long aLong);
}
```

**Expected behavior**
Because the single entity methods are disabled it should not be added to the docs.
```yaml
  /notifications:
    get:
      description: get-notification
    ......
```

**Additional context**
The endpoint is considered enabled because the collection methods are added to the item access methods.
https://github.com/springdoc/springdoc-openapi/blob/60e05121ec1cf9219adf0a91b0a71a8d96b91ad6/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/core/DataRestRouterOperationService.java#L170-L173
I lack the insight of why this is done in the first place.
