### ISSUE TITLE
By moving from 1.5.5 to 1.5.6 I lost auto-generated openapi specs in /v3/api-docs

### ISSUE THREAD

**Issue by jpiccaluga** [springdoc/springdoc-openapi#1115]
By moving from 1.5.5 to 1.5.6 I lost auto-generated openapi specs in /v3/api-docs
In 1.5.5:
call to http://localhost:8181/v3/api-docs/swagger-config/
provides following body:
```
{"configUrl":"/v3/api-docs/swagger-config","oauth2RedirectUrl":"http://localhost:8080/webjars/swagger-ui/oauth2-redirect.html","url":"/v3/api-docs","validatorUrl":""}
```
In 1.5.6:
call to http://localhost:8181/v3/api-docs/swagger-config/
provides following body:
```
{"configUrl":"/v3/api-docs/swagger-config","oauth2RedirectUrl":"http://localhost:8080/webjars/swagger-ui/oauth2-redirect.html","validatorUrl":""}
```

So we lost the url field providing location to openapi spec generated for the project.

Then when calling the endpoint http://localhost:8080/v3/api-docs server response with 404 not found.

I have the following properties:
```
springdoc:
  swagger-ui:
    oauth:
      client-id: <REDACTED>
      use-pkce-with-authorization-code-grant: true
      additional-query-string-params:
        audience: "<REDACTED>"
    oauth-flow:
      authorization-url: "<REDACTED>"
      token-url: "<REDACTED>"
```
Is it a regression or I missed something?

Regards,

Julien
