### ISSUE TITLE
Authorization Bearer token header missing with the use of server.forward-headers-strategy property

### ISSUE THREAD

**Issue by amitoj** [springdoc/springdoc-openapi#1132]
**Describe the bug**
The Swagger UI for Spring boot service deployed on Kubernetes used Pod's IP address

```
curl -X GET "https://10.1.99.2/api/serviceA" -H  "accept: application/json" -H  "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJZZ0NjdUdaVjFDRlVyR...
```

After using the server.forward-headers-strategy property as suggested in [how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy](https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy) the server URL is fixed but the Authorization Bearer token header is missing.

```
curl -X GET "https://www.example.com/api/serviceA" -H  "accept: */*"
``` 

**To Reproduce**
- What version of spring-boot you are using?
2.3.4.RELEASE

- What modules and versions of springdoc-openapi are you using?
1.5.3

The spring boot service OpenAPI security is configured as
```
@SpringBootApplication
@EnableScheduling
@OpenAPIDefinition(info= @Info(title="service-a", version="1.0", description="Service A api"))
@SecurityScheme(
        name = "bearerAuth",
        type = SecuritySchemeType.HTTP,
        bearerFormat = "JWT",
        scheme = "bearer"
)
```

applicaion.yml
```
...
springdoc:
  swagger-ui:
    path: /doc/service-a/swagger-ui.html
    config-url: /doc/service-a/api-docs
  api-docs:
    path: /doc/service-a/api-docs

server:
  forward-headers-strategy: framework
```
