### ISSUE TITLE
Bad request when openapi docs behing Spring Cloud gateway with cloud platform 'Kubernetes'

### ISSUE THREAD

**Issue by aigloss** [springdoc/springdoc-openapi#1223]
Something strange happens when trying to reach OpenAPI specification through a service using Spring Cloud Gateway.

Spring boot version: 2.5.3
Spring Cloud version: 2020.0.3
Springdoc version: 1.5.9

**Steps to Reproduce**

- Create a sample Spring Boot project with Spring cloud gateway ([like this](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.5.3.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=api&name=api&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.api&dependencies=cloud-gateway))
- Create a sample webflux project  ([like this](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.5.3.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=api&name=api&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.api&dependencies=webflux))
- Add the following dependency to the webflux project:
`            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-webflux-ui</artifactId>
                <version>1.5.3</version>
            </dependency>
`
- Configure the webflux project with the following application.yml:

```
server:
  port: 8082

spring:
  application:
    name: admin-service

  main.cloud-platform: kubernetes
```
- Configure the gateway project with the following application.yml:
```
spring:
  cloud:
    gateway:
      routes:
        - id: myapi
          uri: http://localhost:8082
          predicates:
            - Path=/myapi/**
          filters:
            - RewritePath=/myapi/v3/api-docs,/v3/api-docs
```
- Try to access the url [localhost:8080/myapi/v3/api-docs](http://localhost:8080/myapi/v3/api-docs)

**Current behavior**
- The request returns a BAD REQUEST response

**Expected behavior**
- The request returns the OpenAPI specification for the webflux service

**Additional context**
- When toggling out the configuration `spring.main.cloud-platform: kubernetes`, the problem seems solved.
- Having different services behind Spring Cloud Gateway is a very common practice, and exposing all of them through the same page in the gateway is very useful, so it'd be very nice if this can be achieved while CloudPlatform is determined to be Kubernetes (have not tested with other possible values).
- This was working with versions 2.4.x of Spring Boot 

Find attached a sample project for easier reproduction of the issue:
[gateway_openapi_sample.zip](https://github.com/springdoc/springdoc-openapi/files/6878042/gateway_openapi_sample.zip)

Thanks and greetings for your good work!
