### ISSUE TITLE
Default downloadUrl not set 

### ISSUE THREAD

**Issue by Drezir** [springdoc/springdoc-openapi#1241]
Spring boot 2.3.4.RELEASE

**application.yml:**
```yaml
springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        urls:
            - url: /v3/api-docs
              name: default-docs
        urls-primary-name: ${springdoc.swagger-ui.urls[0].name}
```

![image](https://user-images.githubusercontent.com/11374081/129013358-00320972-8496-4f54-959b-10d79928020a.png)

I had to manually type **/v3/api-docs** and hit **Explore** to fetch api doc

http://localhost:8084/v3/api-docs/swagger-config fails on error:
`Type definition error: [simple type, class org.springdoc.core.AbstractSwaggerUiConfigProperties$SwaggerUrl]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.springdoc.core.AbstractSwaggerUiConfigProperties$SwaggerUrl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.TreeMap["urls"]->java.util.LinkedHashSet[0])`
