### ISSUE TITLE
Actuator endpoints generated with a query parameter

### ISSUE THREAD

**Issue by croudet** [springdoc/springdoc-openapi#1272]
**Describe the bug**
-  with ```springdoc.show-actuator=true```
- and actuators endpoints running on the same port with settings:
```
management.server.base-path=/
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/
management.endpoints.enabled-by-default=false
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
management.endpoint.health.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.threaddump.enabled=true
management.endpoint.flyway.enabled=true
```

Then the generated openapi specification file for actuators' endpoints have a parameter:
```
/threaddump:
    get:
      tags:
      - "Actuator"
      summary: "Actuator web endpoint 'threaddump'"
      operationId: "handle_0_1_1"
      parameters:
      - name: "body"
        in: "query"
        required: true
        schema:
          type: "object"
          additionalProperties:
            type: "string"
```

**To Reproduce**
- spring-boot 2.5.4
- springdoc-openapi-wbmvc-core 15.10
