### ISSUE TITLE
Swagger UI issues in 1.6.0+

### ISSUE THREAD

**Issue by s4got10dev** [springdoc/springdoc-openapi#1387]
**Describe the bug**
After updating to 1.6.0 and 1.6.1 in our spring services swagger-ui doesn't render 
Sometimes refreshing multiple times help, but after it works and refresh page in browser it's back to this issue

**To Reproduce**
- Spring Boot 2.6.1 with WebFlux or Web stack
- SpringDoc 1.6.1
- configuration:
```yaml
server:
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  max-http-header-size: 16384

springdoc:
  swagger-ui:
    path: "/api-docs/swagger-ui"
    disable-swagger-default-url: true
    syntax-highlight:
      theme: "arta"
  api-docs:
    path: "/api-docs/v3/openapi"
```

```kotlin
    @Bean
    fun customOpenAPI(): OpenAPI = OpenAPI()
        .info(
            Info().title("API")
                .description("description")
                .contact(Contact().name("My Team").email("my-team@bla-bla.com"))
        )
```

**Expected behavior**
- Swagger UI renders properly just like in version < 1.6.0

**Screenshots**
![image](https://user-images.githubusercontent.com/22197145/146181991-93f3302d-ed05-4290-98d4-f785f36a6c2a.png)

**Additional context**
Nothing specific on logs only this line once UI render definitions properly
```
Init duration for springdoc-openapi is: 676 ms
```
