### ISSUE TITLE
Setting ‘swagger-ui.path’ and ‘swagger-ui.config-url ‘will cause browser to display an incorrect page (Swagger Petstore)

### ISSUE THREAD

**Issue by zxiaozhou** [springdoc/springdoc-openapi#1417]
**Describe the bug**
1. Setting ‘swagger-ui.path’ and ‘swagger-ui.config-url‘ will cause browser to display an incorrect page (swagger Petstore)
2. Configuring only one of them will not cause exceptions

**To Reproduce**
1. https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-book-service project setting ‘swagger-ui.path’ and ‘swagger-ui.config-url‘
2. application.yml
```
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: false
    path: /api/gateway/swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    enabled: true
```
3. Access doc via address http://localhost:8080/api/gateway/swagger-ui.html
4. Error page displayed
![image](https://user-images.githubusercontent.com/62740686/147867051-e99c3972-cace-410a-9102-c858b062c1ce.png)
5. Eventually eliminate the drop-down will open the page request https://petstore.swagger.io/v2/swagger.json directly, not request /v3/api-docs/swagger-config
6. I never defined the https://petstore.swagger.io/v2/swagger.json address

**Help**
I want to customize the UI address, as well as the config-URL address, can give a valid configuration
