### ISSUE TITLE
can access swagger even when disabled - openapi-webflux

### ISSUE THREAD

**Issue by itapai** [springdoc/springdoc-openapi#1454]
I am trying to disable swagger-ui in production by setting `springdoc.api-docs.enabled: false`, but I can still access it via `http://localhost:8080/webjars/swagger-ui/index.html#`

I am using the latest version, `springdoc-openapi-webflux-ui:1.6.4`. Any way to disable this path?

**Comment by bnasslahsen** [comment]
Read this: https://springdoc.org/#disabling-the-swagger-ui

**Comment by itapai** [comment]
I have been through the docs, that's why I'm asking here.
Even when using

```
springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false
```

swagger is still available at `http://localhost:8080/webjars/swagger-ui/index.html#/`
