### ISSUE TITLE
Groups not working in yaml config

### ISSUE THREAD

**Issue by mhewedy** [springdoc/springdoc-openapi#1502]
I don't know how to enable groups, I am using v 1.6.5 (spring boot 2.6.3 and java 17)

Here are the configs

```yaml
springdoc:
  show-actuator: true
  swagger-ui:
    tags-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: -1
    oauth:
      client-id: myClientId
      realm: myRealm
      additional-query-string-params:
        nonce: 123456
  api-docs:
    groups.enabled: true
  group-configs:
    - group: myapi1
      paths-to-match: /api/v1/myapi1/**
    - group: myapi2
      paths-to-match: /api/v1/myapi2/**
```

and here's my spring doc config class:

```java
@OpenAPIDefinition(
        info = @Info(title = "My App", description = "Api Documentation", version = "v1"),
        security = @SecurityRequirement(name = "security_auth"))
@SecurityScheme(
        name = "security_auth",
        type = SecuritySchemeType.OAUTH2,
        flows = @OAuthFlows(implicit = @OAuthFlow(
                authorizationUrl = "path/to/authorizationUrl"
        ))
)
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI customOpenAPI() {
        StringSchema schema = new StringSchema();
        return new OpenAPI()
                .components(new Components()
                        .addParameters("X-User-Id", new HeaderParameter()
                                .required(false)
                                .name("X-User-Id")
                                .schema(schema)
                        ));
    }

    @Bean
    public OpenApiCustomiser customerGlobalHeaderOpenApiCustomizer() {
        return openApi -> openApi.getPaths().values()
                .stream().flatMap(pathItem -> pathItem.readOperations().stream())
                .forEach(it -> it.addParametersItem(new HeaderParameter().$ref("#/components/parameters/X-User-Id")));
    }
}
```
what happens is that I got: "No operations defined in spec!"

I've read in the docs, and followed couple of demo examples, but with no result .. appreciate your support.
