### ISSUE TITLE
tags are not processed correctly

### ISSUE THREAD

**Issue by feferka** [springdoc/springdoc-openapi#1660]
If tags are in original API spec used and generate code, springdoc changes UPPERCASE tags to lowercase, changes tags containing a " " ( space ) to some camelCase and worst it adds both tags into tags list for endpoint definition. Like

```
![image](https://user-images.githubusercontent.com/4493247/167832064-a886e2b8-5c60-49c9-9e45-480d3096fd1f.png)
```

original tags are
```
tags:
  - name: "paired-devices"
    description: Paired Devices Information
```
    
    
    and in endpoint level
    
```
paths:
  "/pairedDevices":
    get:
      tags:
        - "paired-devices"
```
