### ISSUE TITLE
v3/api-docs/swagger-config endpoint without 'url' value

### ISSUE THREAD

**Issue by Jaswine** [springdoc/springdoc-openapi#1698]
hi,developer

**Describe the bug**

i hava the problem with use springdoc and springboot.
springdoc work correctly in local env , but is not work on server.

local env:
http://localhost:8080/user/swagger-ui/index.html

server env 
https://my-domain.com/**sup-user**/user/swagger-ui/index.html

the sup-user is a path mapping

**To Reproduce**
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?

**springboot version:2.6
springdoc version:1.6.8**

- What is the actual and the expected result using OpenAPI Description (yml or json)?

json

- Provide with a sample code (HelloController) or Test that reproduces the problem

config is following:
```
springdoc:
  swagger-ui:
    path: index.html
    enabled: true
    config-url: /sup-user/user/v3/api-docs/swagger-config
    disable-swagger-default-url: true          
    url: /sup-user/user/v3/api-docs
```

**Expected behavior**
- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

local env:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/38072426/172344655-973f428e-f12d-4253-9943-84d068ec8956.png">

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/38072426/172344780-45afe199-e45d-428a-bc97-b2788ae436e3.png">

server env:
![image](https://user-images.githubusercontent.com/38072426/172345014-91572384-e6c1-4e09-be6b-0973916511f7.png)

![image](https://user-images.githubusercontent.com/38072426/172345138-9a320038-db2e-4328-bc21-23160b2b123a.png)

while i insert '/sup-user/user/v3/api-docs' on top of swagger-ui page ,then click 'Explore', i can get all apis info.

![image](https://user-images.githubusercontent.com/38072426/172345588-337a0714-db2c-4081-87b3-ee6d7e329717.png)

**Additional context**
