### ISSUE TITLE
swagger-ui.urls cannot be loaded

### ISSUE THREAD

**Issue by CidTori** [springdoc/springdoc-openapi#1864]
**Describe the bug**
I am using the following `application.yml` properties:
```yaml
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - name: "swagger-v2"
        url: "/v2/api-docs"
      - name: "openapi-v3"
        url: "/v3/api-docs"
```
And a `@Configuration` class containing the beans described [here](https://springdoc.org/faq.html#_what_is_a_proper_way_to_set_up_swagger_ui_to_use_provided_spec_yml).

Sadly, the `urls` property cannot be loaded, it gives the following root cause:

```
org.springframework.beans.InvalidPropertyException: Invalid property 'urls[0]' of bean class [org.springdoc.core.SwaggerUiConfigProperties$$EnhancerBySpringCGLIB$$23737a84]: Cannot get element with index 0 from Set of size 0, accessed using property path 'urls[0]'
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:673)
	... 107 common frames omitted
```

**To Reproduce**
- What version of spring-boot you are using? 1.5.22.RELEASE
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-ui 1.6.11
- What is the actual and the expected result using OpenAPI Description (yml or json)? N/A
- Provide with a sample code (HelloController) or Test that reproduces the problem: I have tested this with [the demo for Spring Boot 1](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-1) with the same error, when adding the same `urls` property.

**Expected behavior**
The application should run

**Comment by CidTori** [comment]
I have tested this with [the demo for Spring Boot 1](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-1) with the same error, when adding the same `urls` property.

**Comment by bnasslahsen** [comment]
@CidTori, 

This will not work with spring-boot-1. There has been so may changes in `AbstractNestablePropertyAccessor`.
If you need these properties with spring spring-boot-1
```
  swagger-ui:
    urls:
      - name: "swagger-v2"
        url: "/v2/api-docs"
      - name: "openapi-v3"
        url: "/v3/api-docs"
```
You will have to inject them programatically to the `SwaggerUiConfigProperties` Bean.
