### ISSUE TITLE
Springdoc no longer picks up required properties in Kotlin classes

### ISSUE THREAD

**Issue by gertjanschouten** [springdoc/springdoc-openapi#2000]
**Describe the bug**

- Springdoc 1.6.13, used with Spring Boot 2.7.5, automatically recognized required properties by looking at whether a property of a class had a "?", indicating that it's optional in Kotlin. Springdoc 2.0.0, used with Spring Boot 3.0.0, no longer does that.

**To Reproduce**
- Unpack the attached zip
- Run with "mvn clean verify -Pspringboot2"
- Inspect the generated openapi.yaml in the base directory. You can see:
```
components:
  schemas:
    Request:
      required:
      - mandatory
      type: object
      properties:
        mandatory:
          type: string
        optional:
          type: string
    Response:
      required:
      - mandatory
      type: object
      properties:
        mandatory:
          type: string
        optional:
          type: string
```
- Now, change the version of spring-boot-starter-parent to "3.0.0" and run it again with "mvn clean verify -Pspringboot3" **(note the different Maven profile)**
- Again inspect the openapi.yml, the "required" properties are gone:
```
components:
  schemas:
    Request:
      type: object
      properties:
        mandatory:
          type: string
        optional:
          type: string
    Response:
      type: object
      properties:
        mandatory:
          type: string
        optional:
          type: string
```

**Expected behavior**

- I expect the funtionality to remain as in Springdoc 1.6.13, used with Spring Boot 2.7.5, in that Springdoc automatically picks up whether a property is required by looking at Kotlin "?" modifiers.

[springdoc-test.zip](https://github.com/springdoc/springdoc-openapi/files/10218261/springdoc-test.zip)
