### ISSUE TITLE
Using springdoc with the Actuator integration causes a deprecation warning

### ISSUE THREAD

**Issue by Okeanos** [springdoc/springdoc-openapi#2024]
**Describe the bug**

- What version of spring-boot you are using? Spring Boot 3.0.1, however, this warning is issued since [2.1.0](https://github.com/spring-projects/spring-boot/issues/14840).
- What modules and versions of springdoc-openapi are you using? Springdoc version 2.0.2 with `springdoc-openapi-starter-webmvc-ui`
- What is the actual and the expected result using OpenAPI Description (yml or json)? not applicable

When using the default configuration for springdoc for the actuator integration a deprecation warning is triggered that complains about invalid characters.

**To Reproduce**

`application.yml`

```yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: true
  use-management-port: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: [ "openapi", "swagger-ui" ]
```

```text
WARN o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'swagger-ui' contains invalid characters, please migrate to a valid format.
```

**Expected behavior**

No warning should be issued.
