### ISSUE TITLE
Springdoc Swagger UI not using swagger-config

### ISSUE THREAD

**Issue by Beckham007** [springdoc/springdoc-openapi#2059]
**Describe the bug**
the same with 
https://stackoverflow.com/questions/71721477/springdoc-swagger-ui-not-using-swagger-config

- What version of spring-boot you are using?
- - 2.7.5
- What modules and versions of springdoc-openapi are you using?
- - 1.6.14

```
springdoc:
  api-docs:
    path: /lstack-demo/swagger/v3/api-docs
  swagger-ui:
    path: /lstack-demo/swagger-ui.html
#    configUrl: /lstack-demo/swagger/v3/api-docs/swagger-config
#    url: /lstack-demo/swagger/v3/api-docs
    disable-swagger-default-url: true
    queryConfigEnabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    displayOperationId: true
```
springdoc-openapi 1.6.6 works well.
springdoc-openapi 1.6.14 get the wrong page to request /v3/api-docs

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/1088944/215522600-67060f1f-1509-43d8-858f-8eb5ba2a9c89.png">
