### ISSUE TITLE
@Schema annotation not working with replaceWithClass

### ISSUE THREAD

**Issue by ypji** [springdoc/springdoc-openapi#2126]
**Describe the bug**

My program heavily uses the `org.bson.types.ObjectId` class, I want it to be recoginzed as a String in the generated documentation. So I used `SpringDocUtils.getConfig().replaceWithClass(ObjectId.class, String.class);`. It worked fine.

But I want to document the fileds of ObjectId by using `@Schema(title = "title")`，but it is ignored.

The only way to solve the problem so far, is removing the `replaceWithClass` section, and using `@Schema(title = "", implemention = String.class)` on each ObjectId field.

**To Reproduce**

- What version of spring-boot you are using? 3.0.4
- What modules and versions of springdoc-openapi are you using? 2.0.3
- What is the actual and the expected result using OpenAPI Description (yml or json)?
```yaml
# actual
components:
  schemas:
    Resp:
      type: object
      properties:
        id1:
          type: string
        id2:
          type: string
# expected
components:
  schemas:
    Resp:
      type: object
      properties:
        id1:
          title: id1 title
          type: string
        id2:
          title: id2 title
          type: string
```

- Provide with a sample code (HelloController) or Test that reproduces the problem
```java
package com.example.sdfsi;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.SchemaProperty;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.Data;
import org.bson.types.ObjectId;
import org.springdoc.core.utils.SpringDocUtils;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.UUID;

@SpringBootApplication
public class SdfsiApplication {
    static {
        SpringDocUtils.getConfig().replaceWithClass(ObjectId.class, String.class);
    }

    public static void main(String[] args) {
        SpringApplication.run(SdfsiApplication.class, args);
    }

    @Data
    public static class Resp {
        @Schema(title = "id of the creator")  // this annotation is ignored
        private ObjectId creatorId;
        @Schema(title = "id of the updater") // this annotation is ignored
        private ObjectId updaterId;
    }

    @RestController
    @RequestMapping("/a")
    @Tag(name = "a")
    public static class AController {
        @GetMapping("/b")
        public Resp b() {
            return new Resp();
        }
    }
}
```
