### ISSUE TITLE
Swagger UI not working after upgrading to Spring boot 3.0.4

### ISSUE THREAD

**Issue by vivek-shetye-pdl** [springdoc/springdoc-openapi#2161]
Upgraded my app to spring boot 3.04 and swagger-ui has stopped working.

using this dependency:
`implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.4'`

My app is being accessed through load balancer and url looks like:
`https://<host_url>.com/qa/api`

And I want swagger to be loaded with following url:
`https://<host_url>.com/qa/api/swagger-ui.html`

My application.yaml file looks like:

```
springdoc:
  swagger-ui:
    configUrl: "/qa/api/v3/api-docs/swagger-config"
    url: "/qa/api/v3/api-docs"
```

this is what I currently see when I try to access swagger-ui:
`https://<host_url>.com/qa/api/swagger-ui.html`
![image](https://user-images.githubusercontent.com/100166390/227249483-04c6316c-0ef0-433b-bae9-13a48d5c5e7e.png)
