### ISSUE TITLE
default-flat-param-object does not take effect

### ISSUE THREAD

**Issue by Charles7c** [springdoc/springdoc-openapi#2181]
If you ❤️ this project consider becoming a [sponsor](https://github.com/sponsors/springdoc).
If you already use the `springdoc-openapi`, please do not forget adding a ***github star*** to this repository.

**Describe the bug**

I upgraded the springdoc-openapi dependencies from 1.6.9 to 1.6.15, and then I tried to use the new feature `default-flat-pam-object`, but it didn't work after the configuration was complete.

**To Reproduce**

- What version of spring-boot you are using?
Spring Boot 2.7.10

- What modules and versions of springdoc-openapi are you using?
springdoc-openapi 1.6.15

- What is the actual and the expected result using OpenAPI Description (yml or json)?
I had to make extensive use of the @ParameterObject annotation before, and I hope that with this configuration I can get rid of this hassle.

- Provide with a sample code (HelloController) or Test that reproduces the problem
```yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    enabled: ${springdoc.swagger-ui.enabled}
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.charles7c.cnadmin.webapi.controller
  default-flat-param-object: true
```
[https://github.com/Charles7c/continew-admin](https://github.com/Charles7c/continew-admin)

**Screenshots**
![image](https://user-images.githubusercontent.com/25446948/228815636-59d53ef5-1228-41b3-9058-92878f221d55.png)
