### ISSUE TITLE
Sort Endpoint alphabetically

### ISSUE THREAD

**Issue by timpamungkas** [springdoc/springdoc-openapi#220]
I am able to sort the tags alphabetically, but how to sort the endpoints (within each tag) alphabetically?

Thanks

**Comment by springdoc** [comment]
Hi, 

 You can use the following springdoc-openapi properties:

```properties
#For sorting endpoints alphabetically
springdoc.swagger-ui.operationsSorter=alpha
#For sorting tags alphabetically
springdoc.swagger-ui.tagsSorter=alpha
```

**Comment by timpamungkas** [comment]
Does not works.
I'm using 1.2.17 with yml configuration (application.yml)

```
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
```
