### ISSUE TITLE
Property Schema Ignored for Basic OpenAPI Type Overrides

### ISSUE THREAD

**Issue by nvinogr** [springdoc/springdoc-openapi#2226]
**Describe the bug**
When applying basic OpenAPI type overrides, the property schema is either ignored or given too low priority, resulting in incomplete documentation. This affects `description`, `title`, `example`, `pattern`, and possibly other schema parameters.

**To Reproduce**
 1. Setup the following configuration:
```kts
// build.gradle.kts
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web") // 3.0.6
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.15.0")
}

openApi {
	apiDocsUrl.set("http://localhost:8080/v3/api-docs.yaml")
	outputFileName.set("openapi.yaml")
}
``` 
> NOTE: same behaviour is present in Springdoc V1

2. Create a demo application:
```kt
@Configuration
@OpenAPIDefinition(info = Info(title = "Demo Application", version = "0.0.1"))
open class OpenApiConfiguration {
    @PostConstruct
    fun customize() {
        SpringDocUtils.getConfig().replaceWithClass(ReplaceWithClass::class.java, String::class.java)
    }
}

@RestController
@RequestMapping("/api")
class HelloController {
    @GetMapping("/schema")
    fun getSchemaResponse(): Response = Response()
}

@Schema(description = "Demo response object")
data class Response(
    @field:Schema(description = "Local schema description (replaceWithClass)")
    val replaceWithClass: ReplaceWithClass = ReplaceWithClass(),
    @field:Schema(description = "Local schema description (\'type\' override)", type = "string")
    val typeOverride: TypeOverride = TypeOverride()
)

@Schema(description = "Class-level schema: ReplaceWithClass")
data class ReplaceWithClass(var str: String = "demo")
@Schema(description = "Class-level schema: TypeOverride")
data class TypeOverride(var str: String = "demo")
```

**Expected behaviour**
The property schema should be used as a source of documentation:
```yaml
components:
  schemas:
    Response:
      type: object
      properties:
        replaceWithClass:
          type: string
          description: Local schema description (replaceWithClass)
        typeOverride:
          type: string
          description: Local schema description (\'type\' override)
      description: Response description
```
 **Actual Behavior**
- `replaceWithClass`: inherits **target class'** Schema (empty for basic types)
- `types` property: inherits **source class'** Schema
```yaml
components:
  schemas:
    Response:
      type: object
      properties:
        replaceWithClass:
          type: string
        typeOverride:
          type: string
          description: "Class-level schema: TypeOverride"
      description: Response description
```

**Additional context**
The `Javadoc` plugin behaves as expected. Replacing data classes with the following code produces the correct output:
```kt
// ...
/** Demo response object */
data class Response(
    /** Local schema description (replaceWithClass) */
    val replaceWithClass: ReplaceWithClass = ReplaceWithClass(),
    /** Local schema description (\'type\' override) */ @field:Schema(type = "string")
    val typeOverride: TypeOverride = TypeOverride()
)

/** Class-level schema: ReplaceWithClass */
data class ReplaceWithClass(var str: String = "demo")
/** Class-level schema: TypeOverride */
data class TypeOverride(var str: String = "demo")
```
Output:
```yaml
components:
  schemas:
    Response:
      type: object
      properties:
        replaceWithClass:
          type: string
          description: Local schema description (replaceWithClass)
        typeOverride:
          type: string
          description: Local schema description (\'type\' override)
      description: Demo response object
```
