### ISSUE TITLE
Schema annotations break when applied to a Boolean field (Kotlin)

### ISSUE THREAD

**Issue by nvinogr** [springdoc/springdoc-openapi#2229]
**Describe the bug**
Schema annotations with `field` use-site break when applied to a Boolean field named `^is.*$`

**To Reproduce**
Demo application:
```kt
@Configuration
@OpenAPIDefinition(info = Info(title = "Demo Application", version = "0.0.1"))
open class OpenApiConfiguration

@RestController
@RequestMapping("/api")
class HelloController {
    @GetMapping("/schema")
    fun getSchemaResponse(): Response = Response()
}

@Schema(description = "Demo response object")
data class Response(
    @field:Schema(description = "My boolean field description", example = "false")
    val isMyBoolean: Boolean = false
)
```

**Expected output**
```yaml
components:
  schemas:
    Response:
      type: object
      properties:
        myBoolean:
          type: boolean
          description: My boolean field description
          example: false
      description: Demo response object
```

**Actual output**
```yaml
components:
  schemas:
    Response:
      type: object
      properties:
        myBoolean:
          type: boolean
      description: Demo response object
```
