### ISSUE TITLE
springdoc-openapi-starter-webmvc-ui 2.1.0 bug

### ISSUE THREAD

**Issue by ldcsaa** [springdoc/springdoc-openapi#2311]
**ENV: spring-booot 3.1.1**

- If both of `server.servlet.context-path` and `spring.mvc.servlet.path` are config to `/`, `/swagger-ui.html` would be rediredted to `//swagger-ui/index.html`, and then Browsers explains it to `http://swagger-ui/index.html`

**To Reproduce**
```
server:
  servlet:
    context-path: /
spring:
  mvc:
    servlet:
      path: /
```
**Screenshots**
![image](https://github.com/springdoc/springdoc-openapi/assets/5990337/3f79db09-7f4b-4a5f-b219-22ddcfd6a2fd)
![image](https://github.com/springdoc/springdoc-openapi/assets/5990337/947dfe82-8faf-438f-8bee-6f7dea1b87b2)
![image](https://github.com/springdoc/springdoc-openapi/assets/5990337/6072dc81-5e73-47c0-a9f2-675dda7c6d9f)
