### ISSUE TITLE
Webflux webjars path cannot be prefixed with a context root

### ISSUE THREAD

**Issue by davidmelia** [springdoc/springdoc-openapi#24]
Regarding the demo springdoc-openapi-test-app3  (3.1.1-SNAPSHOT) if I set the following
```
springdoc:
  api-docs:
    path: /dave/v3/api-docs
  swagger-ui:
    path: /dave/swagger-ui.html     
```

then
`http://localhost:8080/dave/swagger-ui.html`
redirects to
`http://localhost:8080/webjars/swagger-ui/index.html?url=/dave/v3/api-docs&validatorUrl=`
but should be
`http://localhost:8080/dave/webjars/swagger-ui/index.html?url=/dave/v3/api-docs&validatorUrl=`

is this a bug or is it possible to have a parameter to prefix /webjars?

Thanks
