### ISSUE TITLE
request /v3/api-docs Returns the encoded base64 string

### ISSUE THREAD

**Issue by yyyyyyyysssss** [springdoc/springdoc-openapi#2475]
springboot version : 2.7.18

mvc config

```
@Configuration
public class WebMvcConfig extends WebMvcConfigurationSupport {
  @Override
  public void configureMessageConverters(final List<HttpMessageConverter<?>> converters) {
    final FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
    final FastJsonConfig config = new FastJsonConfig();
    final List<MediaType> supportedMediaTypes = new ArrayList<>();
    supportedMediaTypes.add(MediaType.APPLICATION_JSON_UTF8);
    supportedMediaTypes.add(MediaType.APPLICATION_OCTET_STREAM);
    supportedMediaTypes.add(MediaType.APPLICATION_FORM_URLENCODED);
    supportedMediaTypes.add(MediaType.TEXT_HTML);
    converter.setSupportedMediaTypes(supportedMediaTypes);
    config.setSerializerFeatures(
        SerializerFeature.WriteNullNumberAsZero,
        SerializerFeature.PrettyFormat);
    converter.setFastJsonConfig(config);
    converter.setDefaultCharset(StandardCharsets.UTF_8);
    converters.add(converter);
    super.addDefaultHttpMessageConverters(converters);
  }

  @Override
  public void addResourceHandlers(final ResourceHandlerRegistry registry) {
    registry
            .addResourceHandler("/swagger-ui/**")
            .addResourceLocations("classpath:/META-INF/resources/webjars/swagger-ui/4.18.2/");
    super.addResourceHandlers(registry);
  }

}
```
```
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
  packages-to-scan: com.keyrus.bffissuemngt.controller
```
![22b02a6919d39116a68794cca488603](https://github.com/springdoc/springdoc-openapi/assets/105531316/762c81ce-d152-4888-94b2-5245f96fddb4)
