### ISSUE TITLE
swagger-ui.urls not reloaded programmatically

### ISSUE THREAD

**Issue by ernijaime** [springdoc/springdoc-openapi#2637]
**Describe the bug**

When using `SwaggerUiConfigProperties.setUrls()` to add a new URL, the Swagger UI documentation does not get updated with the newly definition. The UI should "hot reload" the definitions.

**To Reproduce**

- What version of spring-boot you are using? `3.2.6`
- What modules and versions of springdoc-openapi are you using? `springdoc-openapi-starter-webflux-ui 2.0.4`
- What is the actual and the expected result using OpenAPI Description (yml or json)? `urls` added on the fly (programmatically) should be added to the ones configured in the `.yml` 
- Provide with a sample code (HelloController) or Test that reproduces the problem

Using version `1.6` the code below used to work for us. When we added a new url programmatically, it refreshed the UI with the new definition (hot reload):

```java
    private void updateSwaggerUiProperties(Collection<PluginOverviewDto> pluginOverviewDtoCollection) {
        Collection<AbstractSwaggerUiConfigProperties.SwaggerUrl> pluginCollection = pluginOverviewDtoCollection.stream().map(pluginOverviewDto ->
                new AbstractSwaggerUiConfigProperties.SwaggerUrl(
                        PluginRouteUtils.getName(pluginOverviewDto),
                        PluginRouteUtils.getBaseUrl(pluginOverviewDto) + "be/v3/api-docs",
                        PluginRouteUtils.getName(pluginOverviewDto))
        ).toList();

        Set<AbstractSwaggerUiConfigProperties.SwaggerUrl> swaggerUrlCollection = this.swaggerUiConfigProperties.getUrls();

        swaggerUrlCollection.addAll(pluginCollection);
        this.swaggerUiConfigProperties.setUrls(swaggerUrlCollection);
    }
```

Currently it does not reload it. This is our `application.yml`:

```yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    queryConfigEnabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    use-root-path: true
    urls:
      - name: xxxx
        url: /suite/xxxx/v0/v3/api-docs
      - name: yyyyy
        url: /suite/yyyyy/v0/v3/api-docs
```

**Expected behavior**

Every time a new URL is added programmatically, it should refresh the UI:

![imagen](https://github.com/springdoc/springdoc-openapi/assets/136598969/7b57e623-1a04-4c66-8825-0bbcbfc9d607)
