### ISSUE TITLE
Java Field Types Default to String with @ParameterObject and @Schema Annotations

### ISSUE THREAD

**Issue by AntuanRokanten** [springdoc/springdoc-openapi#2676]
### Summary
When an object is used as a parameter in a `RestController` and is annotated with `@ParameterObject`, the Java types of the object's fields are ignored if a field is annotated with `@Schema` but does not explicitly specify the `type`. In such cases, the field's type defaults to `string`, regardless of its actual Java type.

### Steps to Reproduce
1. Define a class with fields of various types (e.g., `Integer`, `Boolean`, etc.).
2. Annotate the class fields with `@Schema` without specifying the `type` attribute.
3. Use this class as a parameter in a `RestController` method, and annotate it with `@ParameterObject`.
4. Observe that the OpenAPI documentation generated treats the fields as `string`.

### Expected Behavior
The fields should retain their original Java types unless explicitly overridden by the `type` attribute in the `@Schema` annotation.

### Actual Behavior
The fields default to `string` type in the generated OpenAPI documentation.

### Environment
- **Java version**: 21
- **Spring Boot version**: 3.3.2
- **springdoc-openapi-starter-webmvc-ui version**: 2.6.0

### Additional Context
This behavior was not present in the `springdoc-openapi-common` version `1.6.9`, where the types were correctly inferred from the Java fields.

### Code

Rest controller
```
    @GetMapping
    public String get(@ParameterObject SomeStateObject obj) {
        return obj.toString();
    }
```

Data object
```
@Data
public class SomeStateObject {
    private String state;
    private Integer intObjField;
    private double doublePrimitiveField;
    @Schema(description = "Lorem ipsum dolor sit amet")
    private Double doubleObjField;
    private Boolean booleanObjField;
    private int[] intPrimitiveArray;
}
```
Generated swagger yaml

```
..........
      - name: doubleObjField
        in: query
        description: Lorem ipsum dolor sit amet
        required: false
        schema:
          type: string
          description: Lorem ipsum dolor sit amet
      - name: booleanPrimitiveField
        in: query
        required: false
        schema:
          type: boolean
..........
```
