### ISSUE TITLE
Customize "springdoc.*" properties programatically

### ISSUE THREAD

**Issue by wdallastella** [springdoc/springdoc-openapi#2686]
**Describe the solution you'd like**

Maybe there is already a way of doing it but I didn't find it documented.

Is there any customizer where I can change the `springdoc.*` properties programatically without setting the property?

```
springdoc:
  api-docs:
    path: "/some-other-path/api-docs"
  default-consumes-media-type: "application/json"
  default-produces-media-type: "application/json"
  writer-with-default-pretty-printer: true
```

**Describe alternatives you've considered**

Maybe having a SpringDocCustomizer so we can change those.

**Additional context**

We have some starters for openapi and we could abstract most of the configs on this starter so we don't need to set in all services.
