### ISSUE TITLE
Swagger UI schema type renders as any instead of object when using $ref in modularized YAML configuration

### ISSUE THREAD

**Issue by corock** [springdoc/springdoc-openapi#2743]
## Describe the bug

I'm developing an API server based on Spring Boot and providing OAS 3.1 with Springdoc. Instead of using annotations, I configured OAS 3.1 in YAML format. I successfully modularized the schema specifications by separating them into different files and using the `$ref` property.

However, as shown in the screenshot below, the initial type rendered in the Schema tab of Swagger UI appears as `any`. At first, I thought it might be because `Any` is the top-level type in Kotlin, but when toggling the schema, the `any` type changes to `object`. I suspect that before finding the file via the `$ref` property, the modularized schema is not read, resulting in the initial type being `any`.

When I first modularized, my intention was to set only the `$ref` property in the OAS file. However, due to the issue mentioned above, I'm temporarily setting the `type` property as well. I'm registering this issue to see if there is a nicer solution.

## To Reproduce

- What version of spring-boot you are using?
    - Java 11 / Spring Boot 2.7.14 (The issue seems to be reproducible regardless of the version.)
- What modules and versions of springdoc-openapi are you using?
    - org.springdoc:springdoc-openapi-ui:1.8.0 (Please refer to the additional context.)
- What is the actual and the expected result using OpenAPI Description (yml or json)?
    - The expected result is that the specified schema type should be rendered as `object`, but the actual result is that it is rendered as `any`.
- Provide with a sample code (HelloController) or Test that reproduces the problem
    - To reproduce, create a simple file structure in a Spring Boot project with _application.yaml_, _users.yaml_ (OAS 3.1), and _user.yaml_ (schema file).

**application.yaml**

```yaml
springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    urls:
      - name: users-v1
        url: openapis/users.yaml
```

**resources/static/openapis/users.yaml** (path from content root)

```yaml
openapi: 3.1.0

# (...)

components:
  schemas:
    User:
      # Separate the schema specification into a separate file and reference it using $ref
      $ref: 'components/schemas/users/user.yaml#/components/schemas/User'
```

**resources/static/openapis/components/schemas/users/user.yaml** (path from content root)

```yaml
components:
  schemas:
    User:
      # The type was specified in the separated schema file,
      # but it is not read during the initial rendering in Swagger UI 
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
```

## Expected behavior

The type exposed in the Swagger UI Schema tab should be `object` instead of `any`. (Refer to the Screenshots below)

## Screenshots

| Initial Swagger UI rendering                                                                                       | When selecting Expand All                                                                               | When selecting Collapse again                                                                             |
|--------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------|
| ![initial-rendering-user-schemas](https://github.com/user-attachments/assets/ccee380c-fca3-4709-8d39-cd75a208a0cf) | ![expand-user-schemas](https://github.com/user-attachments/assets/f42eaf1f-2c2a-474f-bde0-180064a75a77) | ![collapse-user-schemas](https://github.com/user-attachments/assets/2125441c-65a6-4401-afd7-9640a3ea4e60) |

## Additional context

I confirmed that the issue persists with the following dependencies:

- Kotlin 1.9 / Spring Boot 3.3.3
- org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0

Also I found a temporary solution as shown below but I'm not sure if I should continue using it this way.

**resources/static/openapis/users.yaml** (path from content root)

```yaml
openapi: 3.1.0

# (...)

components:
  schemas:
    User:
      # Instead of specifying the type in the separated file,
      # it works if the type is specified at the same location as the $ref property.
      type: object
      $ref: 'components/schemas/users/user.yaml#/components/schemas/User'
```
