### ISSUE TITLE
Should this library start defaulting to OpenAPI 3.1?

### ISSUE THREAD

**Issue by ross-paypay** [springdoc/springdoc-openapi#2765]
Currently `springdoc.api-docs.version` defaults to 3.0, but 3.1 has been released multiple years ago.

This can be changed pretty easily by changing the config like:

```yaml
springdoc:
  api-docs:
    version: openapi_3_1
```

I am thinking that perhaps its time to start defaulting to 3.1? 
I suppose this would be a breaking change and would require a major semver bump.
