### ISSUE TITLE
Display Only Actuator Endpoints on Swagger UI

### ISSUE THREAD

**Issue by jorgerod** [springdoc/springdoc-openapi#2766]
Hello,

This issue is primarily a question, though it might also be a feature request. Here is my use case:

I have an application where the management (actuator) is on a different port than the application. The configuration is as follows:

```yaml
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure.include: '*'
server:
  port: 8080

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    group-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true

  show-actuator: true
  cache:
    disabled: true
  use-management-port: true
```

What I would like is that in the application port show only the functional endpoints and in the management port show the actuator endpoints.

![image](https://github.com/user-attachments/assets/5e4bda4e-c926-4c34-a762-be642ad43a54)

I have tried defining a `GroupedOpenApi` bean:

```java
@Bean
public GroupedOpenApi actuatorApi(WebEndpointProperties endpointProperties,
        @Value("${springdoc.version}") String appVersion) {
    return GroupedOpenApi.builder()
            .group("Actuator")
            .pathsToMatch(endpointProperties.getBasePath() + ALL_PATTERN)
            .addOpenApiCustomizer(openApi -> openApi.info(new Info().title("Actuator APIzzz").version(appVersion)))
            .pathsToExclude("/health/**")
            .build();
}
```

But it did not work.
