### ISSUE TITLE
No static resource swagger-ui/index.html error on 2.7.0

### ISSUE THREAD

**Issue by YoungTakhin** [springdoc/springdoc-openapi#2794]
**Describe the bug**

I have same problem with https://github.com/springdoc/springdoc-openapi/issues/2786

My yml file:
```yml
springdoc:
  webjars:
    prefix:
  api-docs:
    path: /v3/api-docs
    resolve-schema-properties: true
    groups:
      enabled: true
  show-actuator: true
  pre-loading-enabled: true
  pre-loading-locales: zh-cn, zh
  disable-i18n: true
  override-with-generic-response: false
  model-converters:
    pageable-converter:
      enabled: true
  swagger-ui:
    use-root-path: true
    persist-authorization: true
    doc-expansion: none
    display-operation-id: true
    disable-swagger-default-url: true
    try-it-out-enabled: true
    filter: true
    displayRequestDuration: true
    show-common-extensions: true
    enabled: true
```

When I inter http://{IP}:{PORT}/swagger-ui/index.html, the console show `No static resource swagger-ui/index.html.`

It's running success with springdoc 2.6.0

**To Reproduce**

- spring-boot-starter-parent from 3.3.5 to 3.4.0
- springdoc-openapi-starter-webmvc-ui from 2.6.0 to 2.7.0
