### ISSUE TITLE
Automatically add required if a field is @notNull or @NotBlank

### ISSUE THREAD

**Issue by lako12** [springdoc/springdoc-openapi#2817]
I have a project with Swagger 3, I noticed a different behavior compared to Swagger 2 and I think it's a bug because with a structure of a certain type, I can make the call to the API, but Swagger doesn't allow me to do it.

I have this API:
```
    @PostMapping(path = "/testOne", consumes = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<String> testOne(@ParameterObject @Valid ClassOne test) {
        return ResponseEntity.ok("ok");
    }
```

```
@Data
public class ClassOne {

    @Valid
    private ClassTwo description;

}
```

```
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class ClassTwo {

    @NotNull
    private String name;
}
```

As you can see, `ClassOne` has an object with the `@Valid` annotation and I am not obliged to pass it (because maybe I want to pass other attributes that I have not added in this example). However, the `@Valid` annotation ensures that if I pass any attribute that is inside that class, then it must respect the rules that I indicate inside (@NotNull etc.). The problem is that on the swagger it says required, even if I do not indicate required and therefore I cannot make the call to the API. This is therefore a problem as I said before, because I may want to send other attributes of `ClassOne`.
This problem occurs only in the case of `@PraameterObject`, while if I use `@RequestBody`, it is not mandatory.

In my opinion swagger should not automatically add requird if an attribute has the annotation `@NotNull` or `@NotBlank`, it should refer to what the user indicates with the annotation @Schema

attached is a zip with an example.
[demo.zip](https://github.com/user-attachments/files/18166665/demo.zip)

**Comment by mc1arke** [comment]
@bnasslahsen This appears to have broken the fix for #2787 as it has returned to only considering the mandatory/optional status of a child field, and not whether the parent object is mandatory/optional. #2787 intended to prevent a field being shown as mandatory if its parent field was not mandatory in a `@ParameterObject` request, which is what was safeguarded in the app233 test that the fix for this has altered.

**Comment by bnasslahsen** [comment]
@mc1arke,

It is expected. I have reviewed the PR, to only consider this behaviour on annotations on the child fields levels, and not on the parent Object level. There is no defined Java rules for that.

**Comment by mc1arke** [comment]
> There is no defined Java rules for that

I'm not sure what you mean by this as it isn't a Java requirement, but a combinatorial logic problem. It may not be stated in a specification but is an implication of the process being followed, namely that in a collapsed structure, something being non-mandatory immediately implies that all child elements are non-mandatory, even if they are directly specified as mandatory.

If it helps, consider the same scenario for 'hidden' fields: a child field cannot be made visible in a collapsed structure if the parent field isn't visible. We have the convenience of being able to short-circuit any further processing on hidden fields but would need to continue processing in the case of the mandatory/non-mandatory status, but would need to end up with a similar outcome.

I think this issue is actually pointing out the same problem as I'd raised in the `Mandatory parameters in non-mandatory parent fields` section of my original issue.

**Comment by bnasslahsen** [comment]
@mc1arke,

The problem is in your combinatorial logic.

From the **Java point of view,** there is no relation between the method parameters annotations and the exploded parameters definitions.
Ideally, after breaking exploding fields parameters, we can only think about preserving the fields annotations.

Your assumption to override the fields annotation by the parameter annotation is wrong.

```java

	@GetMapping("/optional-parent")
	public void nestedParameterObjectWithOptionalParentField(@ParameterObject ParameterObjectWithOptionalField parameters) {

	}

	public record ParameterObjectWithOptionalField(
			@Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED) NestedRequiredParameterObject schemaNotRequiredNestedParameterObject,
			@Parameter NestedRequiredParameterObject parameterNotRequiredNestedParameterObject,
			@Parameter(required = true) NestedRequiredParameterObject requiredNestedParameterObject
	) {

	}

	public record NestedRequiredParameterObject(
			@Schema(requiredMode = Schema.RequiredMode.REQUIRED) @NotNull String requiredParameterField) {
	}

```

Even the `NestedRequiredParameterObject` has `NOT_REQUIRED`, the fields `requiredParameterField` `NestedRequiredParameterObject` from Java point of view, should all be required 

```yaml
  /optional-parent:
    get:
      tags:
        - parameter-controller
      operationId: nestedParameterObjectWithOptionalParentField
      parameters:
        - name: schemaNotRequiredNestedParameterObject.requiredParameterField
          in: query
          required: true
          schema:
            type: string
        - name: parameterNotRequiredNestedParameterObject.requiredParameterField
          in: query
          required: true
          schema:
            type: string
        - name: requiredNestedParameterObject.requiredParameterField
          in: query
          required: true
          schema:
            type: string
```
