### ISSUE TITLE
Add support for deprecated fields

### ISSUE THREAD

**Issue by detomarco** [springdoc/springdoc-openapi#2830]
**Is your feature request related to a problem? Please describe.**
I deprecated a field in Kotlin, I'd like to have the deprecated annotation in the schema

- A clear and concise description of what the problem is. Ex. I'm always frustrated
  when [...]

I defined this data class in Kotlin
```kotlin
data class Car(
     @Deprecated
     val model: String
)
```

- What is the actual result using OpenAPI Description (yml or json)?

```yaml
components:
  schemas:
    Car:
      required:
      - brand
      type: object
      properties:
        brand:
          type: string
```

**Describe the solution you'd like**

```yaml
components:
  schemas:
    Car:
      required:
      - brand
      type: object
      properties:
        brand:
          deprecated: true
          type: string
```
