### ISSUE TITLE
Annotating enum values with @Schema

### ISSUE THREAD

**Issue by kriehzoo** [springdoc/springdoc-openapi#2866]
I tried to put @Schema on an Enum and each of its values.

Version: spring-boot 3.4.1
Version: OpenAPI 3
Version: swagger-annotations-jakarta-2.2.27

However, the description for the enum values is not showing up in the generated JSON.

https://swagger.io/docs/specification/v3_0/data-models/enums/ mentions that the description for the enum values to be put in the description:

quote:
If you need to specify descriptions for enum items, you can do this in the description of the parameter or property:
```
parameters:
  - in: query
    name: sort
    schema:
      type: string
      enum: [asc, desc]
    description: >
      Sort order:
       * `asc` - Ascending, from A to Z
       * `desc` - Descending, from Z to A
```
end quote

I understand that I could include the description of my enum values on all elements using that Enum, but that would lead to duplication.

What do you think about taking the description of each enum value and adding it to the description as quoted above?

Or, is there any other way already of achieving this that I am not aware of, yet?

Thanks.
