### ISSUE TITLE
Ignored allowableValues in @ApiParam

### ISSUE THREAD

**Issue by tfedyanin** [springdoc/springdoc-openapi#29]
As I think, annotation
`@ApiParam(value = "Фильтр по типу продажи", allowableValues = "Аренда, Продажа") @RequestParam(value = "saleTypes",...`
must produce 
```yaml
parameters:
- name: saleTypes
        in: query
        required: false
        description: Фильтр по типу продажи
        schema:
          type: array
          items:
            type: string
            enum:
              - Аренда
              - Продажа
```
but `enum` part is ommited.
