### ISSUE TITLE
Customize Servers via application.yml

### ISSUE THREAD

**Issue by huehnerlady** [springdoc/springdoc-openapi#2948]
**Is your feature request related to a problem? Please describe.**

I would like to change the server URL
For that I found the `ServerBaseUrlCustomizer` mentiones [here](https://springdoc.org/#how-can-i-deploy-springdoc-openapi-starter-webmvc-ui-behind-a-reverse-proxy)
This does not change the description though. 

```
{
  "servers": [
    {
      "url": "https://my-property.test",
      "description": "Generated server url"
    }
  ]
}
```

**Describe the solution you'd like**

I would like to have a application.yml property to be able to change the url including the description:

```
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
  servers: <--
    server1:
        url: https://my-property.test
        description: "my description"
```
