### ISSUE TITLE
Regression: @NotEmpty no longer implies required in OpenAPI schema since 2.8.6

### ISSUE THREAD

**Issue by bvo42** [springdoc/springdoc-openapi#2974]
### Summary

When using `@jakarta.validation.constraints.NotEmpty` on a String field, `springdoc-openapi` currently generates the OpenAPI schema with `minLength: 1`, but it **does not add the field to the `required` array** of the object schema.

This behavior is semantically incomplete:  
`@NotEmpty` **implicitly includes `@NotNull` semantics**, since it fails validation if the value is `null`.

---

### Regression

This used to work correctly **with version 2.8.5** – fields annotated with `@NotEmpty` were included in the `required` array.  
Since 2.8.6, this behavior has changed, and the fields are no longer marked as required unless `@NotNull` or `@Schema(required = true)` is explicitly added.

---

#### Input class

```java
public class ErrorResponseBody {
  @NotEmpty private String error;
  @NotEmpty private String message;
  @NotEmpty private String path;
  @NotNull private Integer status;
  @NotNull private OffsetDateTime timestamp;
}
```

#### Expected OpenAPI output

```yaml
components:
  schemas:
    ErrorResponseBody:
      required:
        - error
        - message
        - path
        - status
        - timestamp
      properties:
        error:
          type: string
          minLength: 1
        ...
```

#### Actual OpenAPI output (since 2.8.6)

```yaml
components:
  schemas:
    ErrorResponseBody:
      required:
        - status
        - timestamp
      properties:
        error:
          type: string
          minLength: 1
        ...
```

---

### Suggested Fix

`springdoc-openapi` should interpret `@NotEmpty` as both:
- `required: true` (in the OpenAPI schema)
- `minLength: 1` or `minItems: 1` (depending on the type)

This would better align with:
- Jakarta Bean Validation semantics (`@NotEmpty` = `@NotNull` + not empty)
- Developer expectations
- Existing code relying on behavior prior to version 2.8.6

---

### Workaround

Currently, developers are forced to redundantly annotate fields like this:

```java
@Schema(required = true)
@NotEmpty
private String error;
```

Or:

```java
@NotNull
@NotEmpty
private String error;
```

This is semantically redundant.
