### ISSUE TITLE
Question: what is a proper way to set up Swagger UI to use provided spec.yml?

### ISSUE THREAD

**Issue by WERT7** [springdoc/springdoc-openapi#358]
Hello. My case is that I do not want the library to generate documentation automatically. Instead, UI should use 'api-spec.yaml' which I made and put in resources folder.

I achieved that with swagger-ui 1.1.49
With properties:
```
springdoc:
  api-docs:
    enabled: false
    path: '/api-docs'
```
And declared a controller that serves /api-docs.

However, this does not work with swagger-ui 1.2.26. Seems like there is a new dependency model now.

The question: is there a proper way to achieve my goal?
