### ISSUE TITLE
@SecurityScheme `paramName` not accounted for the `name`.

### ISSUE THREAD

**Issue by lpandzic** [springdoc/springdoc-openapi#384]
The following:
```
@SecurityScheme(name = "BearerAuthCookie",
        type = SecuritySchemeType.APIKEY,
        in = SecuritySchemeIn.COOKIE,
        paramName = "JWT")
```
does not result into:
```
  securitySchemes:
    BearerAuthCookie:
      type: apiKey
      name: JWT
      in: cookie
```
and instead the name is set to BearerAuthCookie.
See https://github.com/swagger-api/swagger-core/blob/v2.0.4/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/security/SecurityScheme.java#L71

Exact same issue as https://github.com/micronaut-projects/micronaut-openapi/issues/59.
