### ISSUE TITLE
Wrong config URL on remote server

### ISSUE THREAD

**Issue by aoudiamoncef** [springdoc/springdoc-openapi#473]
Hi @bnasslahsen,
I have the configuration below:
```yaml
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
  api-docs:
    enabled: true
    path: api/v1/api-docs
```

When i try to reach my swagger in localhost, redirection works fine but it fails to load remote configuration when i deploy to my remote host:
`my.server.et:48596/swagger-ui/api/v1/api-docs` instead of 
`my.server.et:48596/api/v1/api-docs`

I haven't this issue with SpringFox, so i think that's possible to implement it.

Thanks

**Comment by aoudiamoncef** [comment]
Hi @bnasslahsen, 

I have exactly the same configuration as you said above, but there is a strange behavior when i upload the jar to the remote server which i mentioned it in the issue.

When i hit `my.server.et:48596/swagger` i'm redirected to `my.server.et:48596/swagger-ui/index.html?configUrl=api/v1/api-docs/swagger-config`. It's works great in localhost but never in the remote server. 

Even if i change configUrl property, it doesn't works, the only way is to put the full path in **Explore** section. It's clearly i kind of bug. 

![issue](https://user-images.githubusercontent.com/22281426/75966803-38a60d80-5ecb-11ea-8706-01c13ee84449.PNG)

As you can see, i don't know why a prefix `swagger-ui` is added to the out-coming query ? it's not added in `localhost`

**Expected:** remove the `swagger-ui` prefix from url building. 
**Spring Boot:** 2.2.4.RELEASE
**Springdoc:** 1.2.33 
**Modules:** springdoc-openapi-ui

Thanks

Moncef

**Comment by bnasslahsen** [comment]
Hi @aoudiamoncef, 

 The swagger-ui will not be removed from the url.
 You can rewrite the url if you want using **WebMvcConfigurerAdapter** or **@EnableWebMvc**.

 If you want everything on the UI side to be served from /swagger as prefix.
 You can set the:

```properties
springdoc.swagger-ui.path= /swagger/swagger-ui.html
```

Also, note that the springdoc.api-docs.path should start with **/**

**Comment by aoudiamoncef** [comment]
```yaml
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
    config-url: /api/v1/api-docs
  api-docs:
    enabled: true
    path: /api/v1/api-docs
```
This configuration doesn't work. why ? because this query parameter it's not injected in **Explore** section. So this is why it's inject the default value and i got `my.server.et:48596/swagger-ui/api/v1/api-docs/swagger-config`. When i put explicitly `/api/v1/api-docs` in the **Explore** section, it works. @bnasslahsen, do you get the issue ?

**Comment by bnasslahsen** [comment]
Your configuration is redundant and your config-url doesn't look correct:
Remove:
```yaml
springdoc:
  swagger-ui:
    enabled: true
    config-url: /api/v1/api-docs
  api-docs:
    enabled: true
```
Unable to reproduce your issue. We invite you to review you project configuration.
If you have a Minimal, Reproducible Example, we will be happy to address it:
