### ISSUE TITLE
Wrong path in configUrl param

### ISSUE THREAD

**Issue by kostya05983** [springdoc/springdoc-openapi#484]
**Describe the bug**
When I use custom api-docs path it is inserted wrong in configUrl param

**To Reproduce**
- What version of spring-boot you are using?
2.2.4.RELEASE
- What modules and versions of springdoc-openapi are you using?
```grovy
implementation 'org.springdoc:springdoc-openapi-webflux-ui:1.2.33'
implementation 'org.springdoc:springdoc-openapi-kotlin:1.2.33'
```
- What is the actual and the expected result using OpenAPI Description (yml or json)?
For example when I configure something like this
```yml
springdoc:
  swagger-ui:
    path: /my-api/v2/swagger/swagger-ui.html
  api-docs:
    path: /my-api/v2/swagger/v3/api-docs
```
**Expected behavior**
I expect when I go here `host/my-api/v2/swagger/swagger-ui.html`
I will get `host/my-api/v2/swagger/webjars/swagger-ui/index.html?configUrl=/my-api/v2/swagger/v3/api-docs/swagger-config`
but realy I will get
`host/my-api/v2/swagger/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config`
