### ISSUE TITLE
Improve the support of Pageable

### ISSUE THREAD

**Issue by frankruegamer** [springdoc/springdoc-openapi#499]
**Feature request**
Using springdoc-openapi-data-rest the Pageable object looks like this:

```yaml
Pageable:
      required:
      - page
      - size
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          maximum: 2000
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
```

which is fine. The problem is that it isn't referenced but copied in the schema, when using Pageable as parameter. This will lead to codegenerators (i.e. openapi-generator) to show `object` instead of a Pageable:

```diff
- * @param {Pageable} pageable 
+ * @param {object} pageable 
```

Also none of the attributes of the paged object are marked as required which makes working with them unnecessarily hard.

**Expected behavior**
- Pageable is referenced (not inlined)
- Attributes of the paged and `Sort` model are required

**Additional context**
I wanted to make use of springdoc-openapi-data-rest with webflux after it was supported in v1.2.34.
