### ISSUE TITLE
Optional path variables are marked as required

### ISSUE THREAD

**Issue by macdaddyaz** [springdoc/springdoc-openapi#539]
Hello,

It seems that the `required` parameter of the `@PathVariable` annotation is not being respected. The generated spec always marks the parameter as being required.

**To Reproduce**
The following class demonstrates the issue. This is from a stock Spring Boot project, with only the Web starter and Springdoc as dependencies:

```java
package com.cyberscout.springdocbug;


import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.HashMap;
import java.util.Map;

import static org.springframework.web.bind.annotation.RequestMethod.GET;


@RestController
@RequestMapping("/test")
public class TestController {

    @RequestMapping(path = "/{param}", method = GET)
    public Map<String, String> doIt(@PathVariable(name = "param", required = false) String param) {

        Map<String, String> result = new HashMap<>();
        if (param != null) {
            result.put("param", param);
            result.put("empty", "false");
        }
        else {
            result.put("empty", "true");
        }
        return result;
    }
}
```

This is a snippet of the spec that is generated:

```yaml
paths:
  /test/{param}:
    get:
      # ...
      parameters:
      - name: param
        in: path
        required: true
        schema:
          type: string
```

**Expected behavior**
The path parameter should be marked as optional in the generated spec.

**Comment by bnasslahsen** [comment]
Hi @macdaddyaz, 

 This is conform to the OpenAPI specification.

> Each path parameter must be substituted with an actual value when the client makes an API call. In OpenAPI, a path parameter is defined using in: path. The parameter name must be the same as specified in the path. Also remember to add **required: true**, because path parameters are always required.

You can have a look at the documentation:
- https://swagger.io/docs/specification/describing-parameters/#path-parameters

**Comment by macdaddyaz** [comment]
Ah, I see. I boiled the scenario down too far, then. Consider my original use case:

```java
    @RequestMapping(path = {"/{param}", ""}, method = GET)
    public Map<String, String> doIt(@PathVariable(name = "param", required = false) String param) {
        // ...
    }
```

This method is now mapped to 2 paths: one with the parameter and one without. Springdoc _partially, but incorrectly,_ handles that structure. It generates the following:

```yaml
  /test/{param}:
    get:
      parameters:
      - name: param
        in: path
        required: true
        schema:
          type: string
      # ...
  /test:
    get:
      parameters:
      - name: param
        in: path
        required: true
        schema:
          type: string
      # ...
```

I think that second definition is just wrong. It's declaring a path parameter that isn't present in the declared path. This would be confusing for readers of the documentation, and it messes up client generators like Swagger UI.

(As a side note, I can work around the limitation by splitting the controller methods, and then delegating to one from the other. However, I shouldn't artificially restructure my application logic to support my documentation tool.)
