### ISSUE TITLE
Lazy Initialisation breaks WebFlux support

### ISSUE THREAD

**Issue by jonathannaguin** [springdoc/springdoc-openapi#562]
**Describe the bug**
- If the application has `spring.application.main.lazy-initialization` set to `true`, then it seems the lib drops support for webFlux responses, Mono or Flux.

**To Reproduce**
- What version of spring-boot you are using? **Using Spring Boot 2.2.6.RELEASE.**
- What modules and versions of springdoc-openapi are you using? **org.springdoc:springdoc-openapi-webflux-ui:1.3.2**
- What is the actual and the expected result using OpenAPI Description (yml or json)? **To support Flux or Mono responses.**
- Provide with a sample code (HelloController) or Test that reproduces the problem. **A simple controller code like this:**
```
	@ApiResponses(value = { @ApiResponse(responseCode = "200", description = "get All Tweets") })
	@GetMapping("/tweets")
	public Flux<TweetDTO> getAllTweets() {
		Flux<Tweet> tweet = tweetRepository.findAll();
		return tweetMapper.toDTO(tweet);
	}
```
**Expected behavior**
- A clear and concise description of what you expected to happen. **Regardless of the lazy initialisation setting, the library should behave the same way.**

**Screenshots**

**Additional context**
I tried to debug why this wasn't working and I realized the class `WebFluxSupportConverter` is not getting invoked at all when the Swagger documentation data gets generated. The bean is created but never invoked.

**Comment by bnasslahsen** [comment]
@jonathannaguin, 

  Unable to reproduce. Just tesed on https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-test-app3.

 First of all review your project configuration: This ticket will be closed, and there is no need to reopen a new open for the same issue.

  If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible: You can update your ticket with the necessary information and it will be reopened.

 Please have a look at the contribution guide section Using GitHub Issues:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by jonathannaguin** [comment]
@bnasslahsen I've just tried with the sample app and the problem is there:

![image](https://user-images.githubusercontent.com/265395/79121907-b563bb80-7d96-11ea-8c68-e57fc9c8c109.png)

![image](https://user-images.githubusercontent.com/265395/79121927-beed2380-7d96-11ea-9da6-9f9cf50f8113.png)

The only modification I had to make was on the application.yml:
```
server:
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
spring:
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*
  main:
    lazy-initialization: true
springdoc:
  version: '@springdoc.version@'

```
