### ISSUE TITLE
Honor @JsonTypeInfo @JsonTypeName

### ISSUE THREAD

**Issue by sakibulalam** [springdoc/springdoc-openapi#585]
**Problem/Issue:**
I have a class annotated with `@JsonTypeInfo` to define a wrapper property. But it seems it's not being honored when generating the spec `yaml`/`json`. This is a mismatch with the actual API response.

```kotlin
@Schema(name = "ErrorResponse")
@JsonTypeName(value = "error")
@JsonTypeInfo(include = JsonTypeInfo.As.WRAPPER_OBJECT, use = JsonTypeInfo.Id.NAME)
data class ErrorResponse(
    val message: String,
    val details: List<String>? = null
)
```
The **produced** output is
```yaml
...
components:
  schemas:
    ErrorResponse:
      required:
      - message
      type: object
      properties:
        details:
          type: object
        message:
          type: string
...
```

The **expected** output should be

```yaml
...
components:
  schemas:
    ErrorResponse:
      required: 
        - error
      properties:
        error:
          required:
          - message
          type: object
          properties:
            details:
              type: array
              items:
                type: string
            message:
              type: string
...
```

**Solution:**
When resolving the schema of the classes, the resolver should honor the `@JsonTypeInfo`, `@JsonTypeName` annotation

**Alternatives:**
Right now the only solution I see is to add an additional wrapper class to get it to generate accurate `yaml`/`json`.
