### ISSUE TITLE
Phantom properties added to objects when @JsonSerialize(as =...) implementation uses specific collection subtypes

### ISSUE THREAD

**Issue by chadselph** [springdoc/springdoc-openapi#638]
**Describe the bug**
I have an interface being used for a response and it delegates its JSON encoding to an implementation generated by an annotation processor. The generated swagger doc included an extra property called "empty" of type boolean.

It took me a while to minimize this bug but I've narrowed it down [Immutables](https://immutables.github.io/) using Guava collections. On a class like

```
@Value.Immutable
@JsonSerialize(as = ImmutableMyList.class)
public interface MyList {
  List<String> strings();
}

```

I was getting an extra property on MyList:
```
MyList:
      type: object
      properties:
        strings:
          type: array
          properties:
            empty:
              type: boolean
          items:
            type: string
```

but this minimizes further to

```
import com.google.common.collect.ImmutableList;


@JsonSerialize(as = ItemListImpl.class)
public interface ItemList {
  List<String> getItems();
}

class ItemListImpl implements ItemList {
  @JsonProperty("items")
  public ImmutableList<String> getItems() {
    return ImmutableList.of();
  }
}

```

has the same problem. It actually starts to make a bit of sense when I discovered

```
interface MyFakeList<E> extends List<E> {};
public interface ItemList {
  MyFakeList<String> getMyItems();
}
```

is enough to trigger it as well.

```
    ItemList:
      type: object
      properties:
        myItems:
          type: array
          properties:
            empty:
              type: boolean
          items:
            type: string
```

**To Reproduce**
See code above.
- What version of spring-boot you are using?
2.2.4
- What modules and versions of springdoc-openapi are you using?
1.3.7

**Expected behavior**
Expected 

```
    ItemList:
      type: object
      properties:
        myItems:
          type: array
          items:
            type: string
```

**Additional context**
After minimizing, I'm not actually sure if it's a bug or not, and there's easy work-arounds (in Immutables, `jdkOnly = true`) but it still feels like a bug; a JSON array can't even have properties. But my feelings won't be hurt anymore if you close it as wontfix.
