### ISSUE TITLE
Extra field is shown on a spec

### ISSUE THREAD

**Issue by Strunevskiy** [springdoc/springdoc-openapi#670]
**Describe the bug**
Extra field (write only) is shown on a spec when there is a set method on an object 

**To Reproduce**
- spring-boot - 2.1.4
- springdoc-openapi-ui - 1.3.9

```java
@Schema
public class Status {

  @Schema
  private int code;

  @Schema
  private String message;

  public Status() {}

  public Status(StatusCode statusCode) {
    this.code = statusCode.getCode();
    this.message = statusCode.getMessage();
  }

  public int getCode() {
    return code;
  }

  public String getMessage() {
    return message;
  }

  public void setStatus(StatusCode statusCode) {
    this.code = statusCode.getCode();
    this.message = statusCode.getMessage();
  }
}


public enum StatusCode {
  ENUM_VALUE_1(1, "test1"),
  ENUM_VALUE_2(3, "test2")


}


```

```
Status:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        status:
          type: string
          writeOnly: true
          enum:
           - ENUM_VALUE_1
           - ENUM_VALUE_2
```

**Expected behavior**

```
Status:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```
