### ISSUE TITLE
Springdoc Webflux Core has higher routing priority assigned than Spring Cloud Gateway

### ISSUE THREAD

**Issue by agentS** [springdoc/springdoc-openapi#717]
**Describe the bug**
I tried to follow the [tutorial of Piotr Minkowski on how to document multiple services accessible via a Spring Cloud Gateway instance.](https://piotrminkowski.com/2020/02/20/microservices-api-documentation-with-springdoc-openapi/)
Each of the services exposes an OpenAPI document which can be accessed via `/v3/api-docs`.
To unify the OpenAPI documents in the Spring Cloud Gateway, I tried to create a distinct group for each one of my microservices.
For instance, the microservice named `timetable` is mapped to the group `timetable`.
For accessing the OpenAPI documents of each group, I defined a Spring Cloud Gateway route that leads from the OpenAPI document location on the gateway to the document location on the microservice, e.g. `/v3/api-docs/timetable` is rewritten to `/timetable/v3/api-docs` and a second route takes care of forwarding `/timetable/v3/api-docs` to `http://timetable/v3/api-docs`.
However, Springdoc is assigned a higher priority than Spring Cloud Gateway, so that `/v3/api-docs/timetable` is handled by the Springdoc end point on the gateway instead of being rewritten and proxied as intended.
Disabling Springdoc on the gateway leads to the correct forwarding behaviour, but of course then the OpenAPI documents are not accessible.

**To Reproduce**
- What version of spring-boot you are using?
Spring Boot 2.3.0 with Spring Cloud Hoxton.SR5
- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-webflux-core and springdoc-openapi-webflux-ui
- What is the actual and the expected result using OpenAPI Description (yml or json)?
**Expected result for `/v3/api-docs/timetable`** (with Springdoc disabled or set to a different path):
```yaml
---
openapi: 3.0.1
info:
  title: Timetable API
  contact:
    name: Lukas Schoerghuber
    email: lukas.schoerghuber@posteo.at
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 0.0.0
servers:
- url: http://127.0.0.1:8082
  description: Timetable API development server
tags:
- name: timetable
  description: Timetable-related endpoints
paths:
# ...
```
**Actual result for `/v3/api-docs/timetable`**:
```json
{"openapi":"3.0.1","info":{"title":"OpenAPI definition","version":"v0"},"servers":[{"url":"http://localhost:8081/","description":"Generated server url"}],"paths":{},"components":{}}
```
- Sample code

OpenAPI group configurations:
```java
package eu.nighttrains.gateway.configuration;

import org.springdoc.core.GroupedOpenApi;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class OpenApiConfiguration {
	@Value("${apigateway.path.timetable}")
	private String timetablePath;

	@Value("${apigateway.path.booking}")
	private String bookingPath;

	@Bean
	public GroupedOpenApi timetableApi() {
		return GroupedOpenApi.builder()
				.pathsToMatch(this.timetablePath)
				.group("timetable")
				.build();
	}

	@Bean
	public GroupedOpenApi bookingApi() {
		return GroupedOpenApi.builder()
				.pathsToMatch(this.bookingPath)
				.group("booking")
				.build();
	}
}
```

My spring application configuration:
```yaml
server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
      - id: timetable
        uri: http://localhost:8082/
        predicates:
        - Path=/timetable/**
        filters:
        - StripPrefix=1
        - CircuitBreaker=timetableCircuitBreaker
      - id: timetable
        uri: http://localhost:8084/
        predicates:
        - Path=/booking/**
        filters:
        - StripPrefix=1
        - CircuitBreaker=bookingCircuitBreaker
      - id: openAPI
        uri: http://localhost:${server.port}/
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
```
```properties
apigateway.path.timetable = /timetable/**
apigateway.path.booking = /booking/**

springdoc.api-docs.groups.enabled = true
```

**Expected behavior**
- A clear and concise description of what you expected to happen.
Springdoc takes a higher priority over Spring Cloud Gateway which leads to routes not being rewritten and proxied.
For instance, the path `/v3/api-docs/timeable`, which should first be rewritten to `/timetable/v3/api-docs` and then proxied to `http://timetable/v3/api-docs`, is handled by Springdoc instead of Spring Cloud Gateway.
- What is the expected result using OpenAPI Description (yml or json)?
```yaml
---
openapi: 3.0.1
info:
  title: Timetable API
  contact:
    name: Lukas Schoerghuber
    email: lukas.schoerghuber@posteo.at
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 0.0.0
servers:
- url: http://127.0.0.1:8082
  description: Timetable API development server
tags:
- name: timetable
  description: Timetable-related endpoints
paths:
# ...
```
**Actual result for `/v3/api-docs/timetable`**:
```json
{"openapi":"3.0.1","info":{"title":"OpenAPI definition","version":"v0"},"servers":[{"url":"http://localhost:8081/","description":"Generated server url"}],"paths":{},"components":{}}
```

**Comment by bnasslahsen** [comment]
@agentS, 

 If you don't use the Rewrite rule (which is not mentionned in the tutorial of Piotr Minkowski) , is everything working as expected?

**Comment by agentS** [comment]
Thank you so much for the quick reply. The rewrite rule is required for rewriting the URL of the OpenAPI document of the group to the one of the microservice which is the group's exclusive member. Removing the rewrite filter results in the same result as in my bug report.

The line is indeed mentioned in the tutorial, in the last paragraph of the chapter "Implementation".
Furthermore, the [repository with the code to the tutorial contains the exact same rewrite rule](https://github.com/piomin/sample-spring-microservices-new/blob/62d4e215d9ae3a7db5eb6b0c95d18491591eb0f6/config-service/src/main/resources/config/gateway-service.yml#L43)

**Comment by bnasslahsen** [comment]
@agentS, 

 This is a working sample code using spring-cloud-gateway:
 - https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-microservices

**Comment by agentS** [comment]
Thanks, your updated example solved the issue. Thank you so much for your quick responses!

**Comment by iamshaurya** [comment]
Hi , I have stumbbled upon this same issue
my gateway config contains this 
`routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs`
 But this is not honoured as springdoc webflux routing priority is higher than my routing configs
 
 I followed this article https://piotrminkowski.com/2020/02/20/microservices-api-documentation-with-springdoc-openapi/
 for the setup. 
 Even tried to check the solution at https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-microservices but it seems this link no longer exist.
 
 @agentS can you please help me the working config?

**Comment by iamshaurya** [comment]
And my springdoc config properties looks this:


```
springdoc:
  version: '@springdoc.version@'
  use-root-path: true
  swagger-ui:
    use-root-path: true
  group-configs:
    - group: profile
      pathsToMatch: /profile/**
    - group: schedules
      pathsToMatch: /schedules/**
  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /v3/api-docs
```

**Comment by agentS** [comment]
Hi @iamshaurya,

Honestly, I am out of the loop for this particular problem meaning I don't remember the exact line which fixed the issue. Nevertheless, I can provide you my configuration files which solved the issue.

Here is my YAML configuration for the routes:

```yaml
server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
      - id: timetable
        uri: http://localhost:8082/
        predicates:
        - Path=/timetable/**
        filters:
        - StripPrefix=1
        - CircuitBreaker=timetableCircuitBreaker
      - id: booking
        uri: http://localhost:8084/
        predicates:
        - Path=/booking/**
        filters:
        - StripPrefix=1
        - CircuitBreaker=bookingCircuitBreaker
        - TokenRelay=
      - id: openAPI
        uri: http://localhost:${server.port}/
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs/
opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831

cors:
  origins:
    webFrontend: "http://localhost:3000"
    swaggerUI: "http://localhost:8081"
```

Furthermore, I created a configuration class for the OpenAPI service:

```java
package eu.nighttrains.gateway.configuration;

import org.springdoc.core.GroupedOpenApi;
import org.springdoc.core.SwaggerUiConfigProperties;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.gateway.route.RouteDefinition;
import org.springframework.cloud.gateway.route.RouteDefinitionLocator;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.ArrayList;
import java.util.List;

@Configuration
public class OpenApiConfiguration {
	@Value("${apigateway.path.timetable}")
	private String timetablePath;

	@Value("${apigateway.path.booking}")
	private String bookingPath;

	@Bean
	public List<GroupedOpenApi> apis(SwaggerUiConfigProperties swaggerUiConfigProperties, RouteDefinitionLocator routeDefinitionLocator) {
		List<GroupedOpenApi> groups = new ArrayList<>();
		List<RouteDefinition> definitions = routeDefinitionLocator
				.getRouteDefinitions()
				.collectList()
				.block();
		definitions.stream()
				.filter(routeDefinition ->
						routeDefinition.getId().equals("booking")
						|| routeDefinition.getId().equals("timetable")
				)
				.forEach(routeDefinition -> {
					swaggerUiConfigProperties.addGroup(routeDefinition.getId());
					groups.add(GroupedOpenApi.builder()
						.pathsToMatch("/" + routeDefinition.getId() + "/**")
						.group(routeDefinition.getId())
						.build()
					);
				});
		return groups;
	}
}
```

Finally, I set some general properties required for the entire application:

```ini
spring.application.name = gateway

apigateway.path.timetable = /timetable/**
apigateway.path.booking = /booking/**

springdoc.api-docs.groups.enabled = true
```

Keep in mind that the used library versions are outdated nowadays. Thus, I can not guarantee that the solution works. If you need my entire application, I can provide you a ZIP dump of it.
