### ISSUE TITLE
@PageableDefault does not change Pageable defaults

### ISSUE THREAD

**Issue by frankruegamer** [springdoc/springdoc-openapi#831]
**Describe the bug**
Declaring a Pageable parameter with `@PageableDefaults` will not change the reported default values for `page`, `size`, `sort` in the OpenAPI definition.

**To Reproduce**
- Enable pageable support with `springdoc-openapi-data-rest` or Pageable replacement with `SpringDocUtils`.
- Add a controller and a method with a pageable paramater like so:
```Java
public Page<...> get(@ParameterObject @PageableDefault(size = 5, sort = "name") Pageable pageable) {}
```
- The generated schema will look like this
```yaml
[...]
- name: page
  in: query
  description: Zero-based page index (0..N)
  required: false
  schema:
    minimum: 0
    type: integer
    default: "0"
- name: size
  in: query
  description: The size of the page to be returned
  required: false
  schema:
    minimum: 1
    type: integer
    default: "20"
- name: sort
  in: query
  description: 'Sorting criteria in the format: property(,asc|desc). Default
    sort order is ascending. Multiple sort criteria are supported.'
  required: false
  schema:
    type: array
    items:
      type: string
[...]
```
- calling the controller without specifying pageable parameters will correctly return 5 elements per page

**Expected behavior**
`@PageableDefault` should be recognized to change the defaults for Pageable in the schema.

**Additional context**
Using Springdoc v1.4.4, Spring Webflux 2.2.1.RELEASE.
Default of 20 seems to be coming from `org.springframework.boot.autoconfigure.data.web.SpringDataWebProperties.Pageable#defaultPageSize`.
