### ISSUE TITLE
Regression between 1.1.33 and 1.1.34

### ISSUE THREAD

**Issue by Stexxen** [springdoc/springdoc-openapi#84]
The Following
```java
  @Operation(summary = "Get thing",
          responses = {
                  @ApiResponse(description = "Successful Operation", responseCode = "200",
                          content = @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))),
                  @ApiResponse(responseCode = "404", description = "Not found"),
                  @ApiResponse(responseCode = "401", description = "Authentication Failure")
          }
  )
```

generates this in 1.1.33
```

    200:
          description: Successful Operation
          content:
            application/json:
              schema:
                type: string
        404:
          description: Not found
          content: {}
        401:
          description: Authentication Failure
          content: {}
```

but this in 1.1.34
```
        200:
          description: Successful Operation
          content:
            application/json:
              schema:
                type: string
        404:
          description: Not found
          content:
            '*/*':
              schema:
                type: string
        401:
          description: Authentication Failure
          content:
            '*/*':
              schema:
                type: string
```

Which is rendered as 
![image](https://user-images.githubusercontent.com/4494301/64415505-5ebe3280-d08d-11e9-9054-076fa7c6703f.png)

I think it was caused by #80 but not 100%
