### ISSUE TITLE
Cannot disable Try it out button

### ISSUE THREAD

**Issue by mecseid** [springdoc/springdoc-openapi#844]
**Describe the bug**
As the Swagger UI configuration, to disable Try it out button, we have to set [supportedSubmitMethods ](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-supportedsubmitmethods)as an empty array.
Because of [L199](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/SwaggerUiConfigParameters.java#L199), I can't set an empty array to the property. 

**To Reproduce**
- What version of spring-boot you are using?
2.3.3
- What modules and versions of springdoc-openapi are you using?
Core, UI and Security with version 1.4.5

Minimal configuration to test:
```yaml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    supported-submit-methods: []
```
