### ISSUE TITLE
Endpoints not sorted alphabetically in api-docs json file

### ISSUE THREAD

**Issue by valentinabojan** [springdoc/springdoc-openapi#890]
Hello,

I'm using springdoc-openapi 1.4.8 and I have the following configuration:
```
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /api-docs/intern
```

When I access swagger-ui.html I see all my endpoints are sorted alphabetically by tag name, which is the expected behavior in this case. However, if I access the corresponding json file under /api-docs/intern, the endpoints have a completely different order.

Is there any other configuration I'm missing to achieve this? Thank you!
