### ISSUE TITLE
Byte data type becomes string in the OpenAPI spec; all object properties are declared as optional

### ISSUE THREAD

**Issue by codethief** [springdoc/springdoc-openapi#924]
Hi there! Consider the following REST controller in Kotlin:
```
package com.foo.myrestcontroller

import org.springframework.http.MediaType
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

@RestController
@RequestMapping("/items")
class ItemController {
    @GetMapping("/items", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun getItems(): List<MyItem> {
        // ...
    }
}
```

where `MyItem` is defined as

```
data class MyItem(
    var itemId: Int,
    var someByteValue: Byte,
)
```

The OpenAPI 3.0.1 spec generated by springdoc-openapi v1.4.8 (on spring-boot v2.3.4) is:

```
[…]
components:
  schemas:
    MyItem:
      type: object
      properties:
        itemId:
          type: integer
          format: int32
        someByteValue:
          type: string
          format: byte
```

However, it should read:

```
[…]
components:
  schemas:
    MyItem:
      type: object
      properties:
        itemId:
          type: integer
          format: int32
        someByteValue:
          type: integer
      required:
        - itemId
        - someByteValue
```

That is, 

1. a property of type `Byte` in the code should be represented in the generated schema by an integer, not by a `byte`-formatted string. According to the docs, the latter is something entirely different, namely a [base64-encoded byte sequence of arbitrary length](https://swagger.io/docs/specification/data-models/data-types/#numbers)), whose Kotlin equivalent would probably be a *list* of `Byte`s.

2. All properties should be marked as `required` since they are mandatory in the data class above, too. Right now, since `required` is missing, [all object properties in the above spec are considered optional](https://swagger.io/docs/specification/data-models/data-types/#object) and this will lead to issues when tools like [openapi-generator](https://github.com/OpenAPITools/openapi-generator) generate code in very strongly typed languages like TypeScript, where the resulting interfaces will end up being less strict and will allow properties to be omitted. For instance, in the above case one obtains:

```
export interface MyItem {
    itemId: number?; // <-- Type: number | undefined
    someByteValue: string?; // <-- Type: string | undefined
}
```
