### ISSUE TITLE
custom api-doc url not applied to the default swagger html

### ISSUE THREAD

**Issue by heronman** [springdoc/springdoc-openapi#954]
Hi!

I'm using springdoc 1.5.0 with the following config:
```yaml
springdoc:
  api-docs:
    path: /swagger/v2/my-service/api-doc
  swagger-ui:
    path: /swagger/v2/my-service/swagger-ui.html
    disable-swagger-default-url: true
  paths-to-match: /api/v1/**
  packages-to-scan: my.app.package
```

And when I call the UI, it shows no document.
If I remove `disable-swagger-default-url` property or set it to `false`, the default document is shown - "https://petstore.swagger.io/v2/swagger.json"

I found that SwaggerIndexTransformer replaces that default URL with an empty string in case `disable-swagger-default-url` is set to `true`.
For the moment I'm using the following workaround:
```java
@Configuration
public class SwaggerConfig {
    @Value("${springdoc.api-docs.path}")
    private String apiDocsUrl;

    @Bean
    public SwaggerIndexTransformer indexPageTransformer(
            SwaggerUiConfigProperties swaggerUiConfig,
            SwaggerUiOAuthProperties swaggerUiOAuthProperties,
            ObjectMapper objectMapper
    ) {
        return new SwaggerIndexPageTransformer(swaggerUiConfig, swaggerUiOAuthProperties, objectMapper) {
            @Override
            protected String overwriteSwaggerDefaultUrl(String html) {
                return html.replace(Constants.SWAGGER_UI_DEFAULT_URL, apiDocsUrl);
            }
        };
    }
}
```
But it seems to me it should be the default behavior
